"use strict";(self.webpackChunkairsdk_dev=self.webpackChunkairsdk_dev||[]).push([[30543],{3905:(e,r,t)=>{t.d(r,{Zo:()=>h,kt:()=>u});var n=t(67294);function o(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}function a(e,r){var t=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);r&&(n=n.filter((function(r){return Object.getOwnPropertyDescriptor(e,r).enumerable}))),t.push.apply(t,n)}return t}function i(e){for(var r=1;r<arguments.length;r++){var t=null!=arguments[r]?arguments[r]:{};r%2?a(Object(t),!0).forEach((function(r){o(e,r,t[r])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(t)):a(Object(t)).forEach((function(r){Object.defineProperty(e,r,Object.getOwnPropertyDescriptor(t,r))}))}return e}function s(e,r){if(null==e)return{};var t,n,o=function(e,r){if(null==e)return{};var t,n,o={},a=Object.keys(e);for(n=0;n<a.length;n++)t=a[n],r.indexOf(t)>=0||(o[t]=e[t]);return o}(e,r);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(n=0;n<a.length;n++)t=a[n],r.indexOf(t)>=0||Object.prototype.propertyIsEnumerable.call(e,t)&&(o[t]=e[t])}return o}var c=n.createContext({}),l=function(e){var r=n.useContext(c),t=r;return e&&(t="function"==typeof e?e(r):i(i({},r),e)),t},h=function(e){var r=l(e.components);return n.createElement(c.Provider,{value:r},e.children)},p="mdxType",d={inlineCode:"code",wrapper:function(e){var r=e.children;return n.createElement(n.Fragment,{},r)}},m=n.forwardRef((function(e,r){var t=e.components,o=e.mdxType,a=e.originalType,c=e.parentName,h=s(e,["components","mdxType","originalType","parentName"]),p=l(t),m=o,u=p["".concat(c,".").concat(m)]||p[m]||d[m]||a;return t?n.createElement(u,i(i({ref:r},h),{},{components:t})):n.createElement(u,i({ref:r},h))}));function u(e,r){var t=arguments,o=r&&r.mdxType;if("string"==typeof e||o){var a=t.length,i=new Array(a);i[0]=m;var s={};for(var c in r)hasOwnProperty.call(r,c)&&(s[c]=r[c]);s.originalType=e,s[p]="string"==typeof e?e:o,i[1]=s;for(var l=2;l<a;l++)i[l]=t[l];return n.createElement.apply(null,i)}return n.createElement.apply(null,t)}m.displayName="MDXCreateElement"},14377:(e,r,t)=>{t.r(r),t.d(r,{assets:()=>c,contentTitle:()=>i,default:()=>d,frontMatter:()=>a,metadata:()=>s,toc:()=>l});var n=t(87462),o=(t(67294),t(3905));const a={sidebar_position:5},i="Handling synchronous errors in an application",s={unversionedId:"development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application",id:"development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application",title:"Handling synchronous errors in an application",description:"The most common error handling is synchronous error-handling logic, where you",source:"@site/docs/development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application.md",sourceDirName:"development/core-actionscript-classes/handling-errors",slug:"/development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application",permalink:"/docs/development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application",draft:!1,editUrl:"https://github.com/airsdk/airsdk.dev/edit/main/docs/development/core-actionscript-classes/handling-errors/handling-synchronous-errors-in-an-application.md",tags:[],version:"current",sidebarPosition:5,frontMatter:{sidebar_position:5},sidebar:"mainSidebar",previous:{title:"Working with the debugger versions of Flash runtimes",permalink:"/docs/development/core-actionscript-classes/handling-errors/working-with-the-debugger-versions-of-flash-runtimes"},next:{title:"Creating custom error classes",permalink:"/docs/development/core-actionscript-classes/handling-errors/creating-custom-error-classes"}},c={},l=[{value:"Using try..catch..finally statements",id:"using-trycatchfinally-statements",level:2},{value:"The throw statement",id:"the-throw-statement",level:2},{value:"Displaying a simple error message",id:"displaying-a-simple-error-message",level:2},{value:"Rethrowing errors",id:"rethrowing-errors",level:2}],h={toc:l},p="wrapper";function d(e){let{components:r,...t}=e;return(0,o.kt)(p,(0,n.Z)({},h,t,{components:r,mdxType:"MDXLayout"}),(0,o.kt)("h1",{id:"handling-synchronous-errors-in-an-application"},"Handling synchronous errors in an application"),(0,o.kt)("p",null,"The most common error handling is synchronous error-handling logic, where you\ninsert statements into your code to catch synchronous errors while an\napplication is running. This type of error handling lets your application notice\nand recover from run-time errors when functions fail. The logic for catching a\nsynchronous error includes ",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch..finally")," statements, which literally try\nan operation, catch any error response from the Flash runtime, and finally\nexecute some other operation to handle the failed operation."),(0,o.kt)("h2",{id:"using-trycatchfinally-statements"},"Using try..catch..finally statements"),(0,o.kt)("p",null,"When you work with synchronous run-time errors, use the ",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch..finally"),"\nstatements to catch errors. When a run-time error occurs, the Flash runtime\nthrows an exception, which means that it suspends normal execution and creates a\nspecial object of type Error. The Error object is then thrown to the first\navailable ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," block."),(0,o.kt)("p",null,"The ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," statement encloses statements that have the potential to create\nerrors. You always use the ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement with a ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," statement. If an error\nis detected in one of the statements in the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," statement block, the ",(0,o.kt)("inlineCode",{parentName:"p"},"catch"),"\nstatements that are attached to that ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," statement run."),(0,o.kt)("p",null,"The ",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," statement encloses statements that run whether an error occurs in\nthe ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block. If there is no error, the statements within the ",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," block\nexecute after the ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block statements complete. If there is an error, the\nappropriate ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement executes first, followed by the statements in the\n",(0,o.kt)("inlineCode",{parentName:"p"},"finally")," block."),(0,o.kt)("p",null,"The following code demonstrates the syntax for using the ",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch..finally"),"\nstatements:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},"try\n{\n    // some code that could throw an error\n}\ncatch (err:Error)\n{\n    // code to react to the error\n}\nfinally\n{\n    // Code that runs whether an error was thrown. This code can clean\n    // up after the error, or take steps to keep the application running.\n}\n")),(0,o.kt)("p",null,"Each ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement identifies a specific type of exception that it handles.\nThe ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement can specify only error classes that are subclasses of the\nError class. Each ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement is checked in order. Only the first ",(0,o.kt)("inlineCode",{parentName:"p"},"catch"),"\nstatement that matches the type of error thrown runs. In other words, if you\nfirst check the higher-level Error class and then a subclass of the Error class,\nonly the higher-level Error class matches. The following code illustrates this\npoint:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},'try\n{\n    throw new ArgumentError("I am an ArgumentError");\n}\ncatch (error:Error)\n{\n    trace("<Error> " + error.message);\n}\ncatch (error:ArgumentError)\n{\n    trace("<ArgumentError> " + error.message);\n}\n')),(0,o.kt)("p",null,"The previous code displays the following output:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},"<Error> I am an ArgumentError\n")),(0,o.kt)("p",null,"To correctly catch the ArgumentError, make sure that the most specific error\ntypes are listed first and the more generic error types are listed later, as the\nfollowing code shows:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},'try\n{\n    throw new ArgumentError("I am an ArgumentError");\n}\ncatch (error:ArgumentError)\n{\n    trace("<ArgumentError> " + error.message);\n}\ncatch (error:Error)\n{\n    trace("<Error> " + error.message);\n}\n')),(0,o.kt)("p",null,"Several methods and properties in the ActionScript API throw run-time errors if\nthey encounter errors while they execute. For example, the ",(0,o.kt)("inlineCode",{parentName:"p"},"close()")," method in\nthe Sound class throws an IOError if the method is unable to close the audio\nstream, as demonstrated in the following code:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},"var mySound:Sound = new Sound();\ntry\n{\n    mySound.close();\n}\ncatch (error:IOError)\n{\n    // Error #2029: This URLStream object does not have an open stream.\n}\n")),(0,o.kt)("p",null,"As you become more familiar with the\n",(0,o.kt)("a",{parentName:"p",href:"https://airsdk.dev/reference/actionscript/3.0/index.html"},"ActionScript 3.0 Reference for the Adobe Flash Platform"),",\nyou'll notice which methods throw exceptions, as detailed in each method's\ndescription."),(0,o.kt)("h2",{id:"the-throw-statement"},"The throw statement"),(0,o.kt)("p",null,"Flash runtimes throw exceptions when they encounter errors in your running\napplication. In addition, you can explicitly throw exceptions yourself using the\n",(0,o.kt)("inlineCode",{parentName:"p"},"throw")," statement. When explicitly throwing errors, Adobe recommends that you\nthrow instances of the Error class or its subclasses. The following code\ndemonstrates a ",(0,o.kt)("inlineCode",{parentName:"p"},"throw")," statement that throws an instance of the Error class,\n",(0,o.kt)("inlineCode",{parentName:"p"},"MyErr"),", and eventually calls a function, ",(0,o.kt)("inlineCode",{parentName:"p"},"myFunction()"),", to respond after the\nerror is thrown:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},'var MyError:Error = new Error("Encountered an error with the numUsers value", 99);\nvar numUsers:uint = 0;\ntry\n{\n    if (numUsers == 0)\n    {\n        trace("numUsers equals 0");\n    }\n}\ncatch (error:uint)\n{\n    throw MyError; // Catch unsigned integer errors.\n}\ncatch (error:int)\n{\n    throw MyError; // Catch integer errors.\n}\ncatch (error:Number)\n{\n    throw MyError; // Catch number errors.\n}\ncatch (error:*)\n{\n    throw MyError; // Catch any other error.\n}\nfinally\n{\n    myFunction(); // Perform any necessary cleanup here.\n}\n')),(0,o.kt)("p",null,"Notice that the ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statements are ordered so that the most specific data\ntypes are listed first. If the ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," statement for the Number data type is\nlisted first, neither the catch statement for the uint data type nor the catch\nstatement for the int data type is ever run."),(0,o.kt)("p",null,"Note: In the Java programming language, each function that can throw an\nexception must declare this fact, listing the exception classes it can throw in\na ",(0,o.kt)("inlineCode",{parentName:"p"},"throws")," clause attached to the function declaration. ActionScript does not\nrequire you to declare the exceptions thrown by a function."),(0,o.kt)("h2",{id:"displaying-a-simple-error-message"},"Displaying a simple error message"),(0,o.kt)("p",null,"One of the biggest benefits of the new exception and error event model is that\nit allows you to tell users when and why an action has failed. Your part is to\nwrite the code to display the message and offer options in response."),(0,o.kt)("p",null,"The following code shows a simple ",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch")," statement to display the error in\na text field:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},'package\n{\n    import flash.display.Sprite;\n    import flash.text.TextField;\n\n    public class SimpleError extends Sprite\n    {\n        public var employee:XML =\n            <EmpCode>\n                <costCenter>1234</costCenter>\n                <costCenter>1-234</costCenter>\n            </EmpCode>;\n\n        public function SimpleError()\n        {\n            try\n            {\n                if (employee.costCenter.length() != 1)\n                {\n                    throw new Error("Error, employee must have exactly one cost center assigned.");\n                }\n            }\n            catch (error:Error)\n            {\n                var errorMessage:TextField = new TextField();\n                errorMessage.autoSize = TextFieldAutoSize.LEFT;\n                errorMessage.textColor = 0xFF0000;\n                errorMessage.text = error.message;\n                addChild(errorMessage);\n            }\n        }\n    }\n}\n')),(0,o.kt)("p",null,"Using a wider range of error classes and built-in compiler errors, ActionScript\n3.0 offers more information than previous versions of ActionScript about why\nsomething has failed. This information enables you to build more stable\napplications with better error handling."),(0,o.kt)("h2",{id:"rethrowing-errors"},"Rethrowing errors"),(0,o.kt)("p",null,"When you build applications, there are several occasions in which you need to\nrethrow an error if you are unable to handle the error properly. For example,\nthe following code shows a nested ",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch")," block, which rethrows a custom\nApplicationError if the nested ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," block is unable to handle the error:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},'try\n{\n    try\n    {\n        trace("<< try >>");\n        throw new ApplicationError("some error which will be rethrown");\n    }\n    catch (error:ApplicationError)\n    {\n        trace("<< catch >> " + error);\n        trace("<< throw >>");\n        throw error;\n    }\n    catch (error:Error)\n    {\n        trace("<< Error >> " + error);\n    }\n}\ncatch (error:ApplicationError)\n{\n    trace("<< catch >> " + error);\n}\n')),(0,o.kt)("p",null,"The output from the previous snippet would be the following:"),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre"},"<< try >>\n<< catch >> ApplicationError: some error which will be rethrown\n<< throw >>\n<< catch >> ApplicationError: some error which will be rethrown\n")),(0,o.kt)("p",null,"The nested ",(0,o.kt)("inlineCode",{parentName:"p"},"try")," block throws a custom ApplicationError error that is caught by\nthe subsequent ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," block. This nested ",(0,o.kt)("inlineCode",{parentName:"p"},"catch")," block can try to handle the\nerror, and if unsuccessful, throw the ApplicationError object to the enclosing\n",(0,o.kt)("inlineCode",{parentName:"p"},"try..catch")," block."))}d.isMDXComponent=!0}}]);